In [1]:
from google.colab import files
uploaded = files.upload()

Saving vacancies_merged.csv to vacancies_merged.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('vacancies_merged.csv')

In [4]:
df

,profession,profession_full,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,"Компания ""Санкт-Петербургская биржа"" Вам предс...",NaN,NaN,NaN,scramping
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",NaN,NaN,NaN,scramping
2,Специалист,Middle+ AQA специалист,2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",NaN,NaN,NaN,scramping
3,Технолог,Технолог( АКРИХИН ),2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",NaN,NaN,NaN,scramping
4,Project manager,Project Manager Game Dev( Beresnev Games ),2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,"Компания ""Beresnev Games"" Мы в поиске Project ...",NaN,NaN,NaN,scramping
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30807,Практикант / стажёр Документовед,Практикант / стажёр Документовед,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api
30808,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api
30809,Стажер в IT отдел,Стажер в IT отдел,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api
30810,Сотрудник технической поддержки,Сотрудник технической поддержки,2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api
30811,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api

In [5]:
df['company_description']

0        Компания "Санкт-Петербургская биржа" Вам предс...
1        Компания "ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ"...
2        Компания "Компания Ритейл Сервис" Мы - аккреди...
3        Компания "АКРИХИН" Обязанности:  Обеспечивать ...
4        Компания "Beresnev Games" Мы в поиске Project ...
                               ...
30807    Российская государственная корпорация, объедин...
30808    Наша Школа - это пространство возможностей, тв...
30809    Ведущий российский бренд безалкогольных напитк...
30810    Lasertech — один из ведущих игроков на рынке п...
30811    Производство специальных жидкостей для автомоб...
Name: company_description, Length: 30812, dtype: object

In [6]:
import re

In [7]:
if 'dms' in df.columns:
    df = df.drop('dms', axis=1)
slow = r'дмс|медицинск.*страхов.*'
df['dms'] = 0
for ind in df.index:
  opis = df['company_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(slow, opis, re.IGNORECASE):
      df.loc[ind, 'dms'] = 1
df['dms'].sum()

#https://sky.pro/wiki/python/osnovnye-funkcii-i-metody-modulya-re/ регулярные выражениизучила тут

np.int64(9863)

In [8]:
df

,profession,profession_full,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,"Компания ""Санкт-Петербургская биржа"" Вам предс...",NaN,NaN,NaN,scramping,1
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",NaN,NaN,NaN,scramping,1
2,Специалист,Middle+ AQA специалист,2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",NaN,NaN,NaN,scramping,0
3,Технолог,Технолог( АКРИХИН ),2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",NaN,NaN,NaN,scramping,1
4,Project manager,Project Manager Game Dev( Beresnev Games ),2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,"Компания ""Beresnev Games"" Мы в поиске Project ...",NaN,NaN,NaN,scramping,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30807,Практикант / стажёр Документовед,Практикант / стажёр Документовед,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,0
30808,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0
30809,Стажер в IT отдел,Стажер в IT отдел,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0
30810,Сотрудник технической поддержки,Сотрудник технической поддержки,2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0
30811,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0

In [9]:
if 'ai' in df.columns:
    df = df.drop('ai', axis=1)
slow = r'\bai\b|\bai(?=-)|\bai(?= )|\bии\b|искусственн.*интеллект.*|\bml\b|машинно.*обучен.*|генеративн.*модел.*|\bllm\b|нейросет.*|\bdl\b|deep learning|\bnlp\b|generative ai|computer vision|нейронны.*сет.*'
df['ai'] = 0
for ind in df.index:
  opis = df['company_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(slow, opis, re.IGNORECASE):
      df.loc[ind, 'ai'] = 1
df['ai'].sum()

#предположила что есть вариант что написано что-то типо ai-... или ai ..., поэтому обратилась к статье:
#https://habr.com/ru/articles/956068/

np.int64(2580)

In [10]:
df

,profession,profession_full,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,"Компания ""Санкт-Петербургская биржа"" Вам предс...",NaN,NaN,NaN,scramping,1,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",NaN,NaN,NaN,scramping,1,0
2,Специалист,Middle+ AQA специалист,2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",NaN,NaN,NaN,scramping,0,0
3,Технолог,Технолог( АКРИХИН ),2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",NaN,NaN,NaN,scramping,1,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,"Компания ""Beresnev Games"" Мы в поиске Project ...",NaN,NaN,NaN,scramping,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30807,Практикант / стажёр Документовед,Практикант / стажёр Документовед,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,0,0
30808,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0
30809,Стажер в IT отдел,Стажер в IT отдел,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0
30810,Сотрудник технической поддержки,Сотрудник технической поддержки,2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0
30811,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0

In [11]:
if 'work_format' in df.columns:
    df = df.drop('work_format', axis=1)
slowg = r'гибри.*|частично удал.*|смешанный вариант|смешанный режим работы|смешанный формат'
slowr = r'удален.*|удалён.*|remote work|работа из дома'
df['work_format'] = 0
for ind in df.index:
  opis = df['company_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(slowr, opis, re.IGNORECASE):
      df.loc[ind, 'work_format'] = 2
    elif re.search(slowg, opis, re.IGNORECASE):
      df.loc[ind, 'work_format'] = 1

In [13]:
df

,profession,profession_full,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,"Компания ""Санкт-Петербургская биржа"" Вам предс...",NaN,NaN,NaN,scramping,1,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",NaN,NaN,NaN,scramping,1,0,0
2,Специалист,Middle+ AQA специалист,2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",NaN,NaN,NaN,scramping,0,0,2
3,Технолог,Технолог( АКРИХИН ),2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",NaN,NaN,NaN,scramping,1,0,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,"Компания ""Beresnev Games"" Мы в поиске Project ...",NaN,NaN,NaN,scramping,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30807,Практикант / стажёр Документовед,Практикант / стажёр Документовед,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,0,0,0
30808,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0
30809,Стажер в IT отдел,Стажер в IT отдел,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0
30810,Сотрудник технической поддержки,Сотрудник технической поддержки,2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0
30811,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0

In [14]:
if 'education' in df.columns:
    df = df.drop('education', axis=1)
v = r'высшее'
sr = r'среднее'
df['education'] = 0
for ind in df.index:
  opis = df['company_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(sr, opis, re.IGNORECASE):
      df.loc[ind, 'education'] = 1
    elif re.search(v, opis, re.IGNORECASE):
      df.loc[ind, 'education'] = 2

In [16]:
df

,profession,profession_full,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,"Компания ""Санкт-Петербургская биржа"" Вам предс...",NaN,NaN,NaN,scramping,1,0,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",NaN,NaN,NaN,scramping,1,0,0,0
2,Специалист,Middle+ AQA специалист,2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",NaN,NaN,NaN,scramping,0,0,2,0
3,Технолог,Технолог( АКРИХИН ),2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",NaN,NaN,NaN,scramping,1,0,0,2
4,Project manager,Project Manager Game Dev( Beresnev Games ),2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,"Компания ""Beresnev Games"" Мы в поиске Project ...",NaN,NaN,NaN,scramping,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30807,Практикант / стажёр Документовед,Практикант / стажёр Документовед,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,0,0,0,0
30808,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0
30809,Стажер в IT отдел,Стажер в IT отдел,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0
30810,Сотрудник технической поддержки,Сотрудник технической поддержки,2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0
30811,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0

In [17]:
if '1с' in df.columns:
    df = df.drop('1с', axis=1)
c = r'\b1с.*|\b1c.*'
df['1с'] = 0
for ind in df.index:
  opis = df['company_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(c, opis, re.IGNORECASE):
      df.loc[ind, '1с'] = 1
df['1с'].sum()

np.int64(3539)

In [18]:
df

,profession,profession_full,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education,1с
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,"Компания ""Санкт-Петербургская биржа"" Вам предс...",NaN,NaN,NaN,scramping,1,0,0,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",NaN,NaN,NaN,scramping,1,0,0,0,0
2,Специалист,Middle+ AQA специалист,2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",NaN,NaN,NaN,scramping,0,0,2,0,0
3,Технолог,Технолог( АКРИХИН ),2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",NaN,NaN,NaN,scramping,1,0,0,2,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,"Компания ""Beresnev Games"" Мы в поиске Project ...",NaN,NaN,NaN,scramping,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30807,Практикант / стажёр Документовед,Практикант / стажёр Документовед,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,0,0,0,0,0
30808,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30809,Стажер в IT отдел,Стажер в IT отдел,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30810,Сотрудник технической поддержки,Сотрудник технической поддержки,2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30811,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0

In [30]:
df.to_csv('vacancies_merged_prizn.csv', encoding='utf-8')

In [31]:
files.download('vacancies_merged_prizn.csv')

In [32]:
df

,profession,profession_full,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education,1с
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,"Компания ""Санкт-Петербургская биржа"" Вам предс...",NaN,NaN,NaN,scramping,1,0,0,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",NaN,NaN,NaN,scramping,1,0,0,0,0
2,Специалист,Middle+ AQA специалист,2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",NaN,NaN,NaN,scramping,0,0,2,0,0
3,Технолог,Технолог( АКРИХИН ),2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",NaN,NaN,NaN,scramping,1,0,0,2,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,"Компания ""Beresnev Games"" Мы в поиске Project ...",NaN,NaN,NaN,scramping,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30807,Практикант / стажёр Документовед,Практикант / стажёр Документовед,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,0,0,0,0,0
30808,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30809,Стажер в IT отдел,Стажер в IT отдел,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30810,Сотрудник технической поддержки,Сотрудник технической поддержки,2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30811,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0