In [ ]:
from google.colab import files
uploaded = files.upload()

Saving vacancies_merged.csv to vacancies_merged.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('vacancies_merged.csv')

In [ ]:
df

,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education,1с
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,NaN,NaN,NaN,NaN,scrapping,1,0,0,2,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0,0,0,0
30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0,1,0,0
30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,1,1
30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,1

In [ ]:
df['vacancy_description']

0        Компания "Санкт-Петербургская биржа" Вам предс...
1        Компания "ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ"...
2        Компания "Компания Ритейл Сервис" Мы - аккреди...
3        Компания "АКРИХИН" Обязанности:  Обеспечивать ...
4        Компания "Beresnev Games" Мы в поиске Project ...
                               ...
30862    ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...
30863    Обязанности:\n• Установка, обновление и админи...
30864    Здесь занимаются поддержкой IT-платформ и их р...
30865    Добрый день!\nМы компания Lasertech, занимаемс...
30866    Обязанности:\n• \n• Работа в системах: 1С, Чес...
Name: vacancy_description, Length: 30867, dtype: object

In [ ]:
import re

In [ ]:
if 'dms' in df.columns:
    df = df.drop('dms', axis=1)
slow = r'дмс|медицинск.*страхов.*'
df['dms'] = 0
for ind in df.index:
  opis = df['vacancy_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(slow, opis, re.IGNORECASE):
      df.loc[ind, 'dms'] = 1
df['dms'].sum()

#https://sky.pro/wiki/python/osnovnye-funkcii-i-metody-modulya-re/ регулярные выражениизучила тут

np.int64(12029)

In [ ]:
df

,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,NaN,NaN,NaN,NaN,scrapping,1
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,NaN,NaN,NaN,NaN,scrapping,1
2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,NaN,NaN,NaN,NaN,scrapping,0
3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,NaN,NaN,NaN,NaN,scrapping,1
4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,NaN,NaN,NaN,NaN,scrapping,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1
30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0
30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1
30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0
30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0

In [ ]:
if 'ai' in df.columns:
    df = df.drop('ai', axis=1)
slow = r'\bai\b|\bai(?=-)|\bai(?= )|\bии\b|искусственн.*интеллект.*|\bml\b|машинно.*обучен.*|генеративн.*модел.*|\bllm\b|нейросет.*|\bdl\b|deep learning|\bnlp\b|generative ai|computer vision|нейронны.*сет.*'
df['ai'] = 0
for ind in df.index:
  opis = df['vacancy_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(slow, opis, re.IGNORECASE):
      df.loc[ind, 'ai'] = 1
df['ai'].sum()

#предположила что есть вариант что написано что-то типо ai-... или ai ..., поэтому обратилась к статье:
#https://habr.com/ru/articles/956068/

np.int64(2209)

In [ ]:
df

,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,NaN,NaN,NaN,NaN,scrapping,1,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,NaN,NaN,NaN,NaN,scrapping,1,0
2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,NaN,NaN,NaN,NaN,scrapping,0,0
3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,NaN,NaN,NaN,NaN,scrapping,1,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,NaN,NaN,NaN,NaN,scrapping,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0
30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0
30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0
30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0
30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0

In [ ]:
if 'work_format' in df.columns:
    df = df.drop('work_format', axis=1)
slowg = r'гибри.*|частично удал.*|смешанный вариант|смешанный режим работы|смешанный формат'
slowr = r'удален.*|удалён.*|remote work|работа из дома'
df['work_format'] = 0
for ind in df.index:
  opis = df['vacancy_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(slowr, opis, re.IGNORECASE):
      df.loc[ind, 'work_format'] = 2
    elif re.search(slowg, opis, re.IGNORECASE):
      df.loc[ind, 'work_format'] = 1

In [ ]:
df

,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,NaN,NaN,NaN,NaN,scrapping,1,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,NaN,NaN,NaN,NaN,scrapping,1,0,0
2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,NaN,NaN,NaN,NaN,scrapping,0,0,2
3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,NaN,NaN,NaN,NaN,scrapping,1,0,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,NaN,NaN,NaN,NaN,scrapping,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0,0
30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0
30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0,1
30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0
30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0

In [ ]:
if 'education' in df.columns:
    df = df.drop('education', axis=1)
v = r'высшее'
sr = r'среднее'
df['education'] = 0
for ind in df.index:
  opis = df['vacancy_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(sr, opis, re.IGNORECASE):
      df.loc[ind, 'education'] = 1
    elif re.search(v, opis, re.IGNORECASE):
      df.loc[ind, 'education'] = 2

In [ ]:
df

,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,NaN,NaN,NaN,NaN,scrapping,1,0,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,NaN,NaN,NaN,NaN,scrapping,1,0,0,0
2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,NaN,NaN,NaN,NaN,scrapping,0,0,2,0
3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,NaN,NaN,NaN,NaN,scrapping,1,0,0,2
4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,NaN,NaN,NaN,NaN,scrapping,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0,0,0
30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0
30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0,1,0
30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,1
30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0

In [ ]:
if '1с' in df.columns:
    df = df.drop('1с', axis=1)
c = r'\b1с.*|\b1c.*'
df['1с'] = 0
for ind in df.index:
  opis = df['vacancy_description'].iloc[ind]
  if pd.notna(opis):
    if re.search(c, opis, re.IGNORECASE):
      df.loc[ind, '1с'] = 1
df['1с'].sum()

np.int64(3818)

In [ ]:
df

,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education,1с
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,NaN,NaN,NaN,NaN,scrapping,1,0,0,2,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0,0,0,0
30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0,1,0,0
30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,1,1
30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,1

In [ ]:
df.to_csv('vacancies_merged_prizn.csv', encoding='utf-8')

In [ ]:
files.download('vacancies_merged_prizn.csv')

In [ ]:
df

,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,company_name,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education,1с
0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,Санкт-Петербургская биржа,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,Компания Ритейл Сервис,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,АКРИХИН,NaN,NaN,NaN,NaN,scrapping,1,0,0,2,0
4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,Beresnev Games,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Росатом,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0,0,0,0
30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",ГБОУ Школа № 657,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Добрый,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0,1,0,0
30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",Lasertech,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,1,1
30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...","""ПКФ ""Аметист+""",Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,1